# Generated by Django 2.2.2 on 2019-06-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('question', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
            },
        ),
    ]
