# Generated by Django 2.2.2 on 2019-06-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190613_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
